local uv = require("luv")
local bridge = require("herdr_mail")
local runtime = require("herdr_watch")
describe("durable mail notice", function()
	it("writes atomically with private mode, rejecting symlink inboxes", function()
		local root = assert(uv.fs_mkdtemp((os.getenv("TMPDIR") or "/tmp") .. "/mail-notice-XXXXXX"))
		local datetime = "2026-09-10T16:00:00-04:00"
		local body = bridge.render("validate", 1, datetime, {})
		local path = runtime.write_notice(root, "validate", body, datetime)
		local file = assert(io.open(path)); assert.equal(body, file:read("*a")); file:close()
		assert.equal(384, uv.fs_stat(path).mode % 512)
		assert.equal(path, runtime.write_notice(root, "validate", body, datetime))
		assert(uv.fs_unlink(path)); assert(uv.fs_rmdir(root .. "/inbox"))
		assert(uv.fs_symlink(root, root .. "/inbox"))
		assert.has_error(function() runtime.write_notice(root, "validate", body, datetime) end)
		assert(uv.fs_unlink(root .. "/inbox")); assert(uv.fs_rmdir(root))
	end)
end)
