local workers = require("wake_workers")
describe("bounded wake workers", function()
	it("starts only two, keeps results, and frees capacity without duplicate launch", function()
		local starts, callbacks = {}, {}
		local pool = workers.new(function(task, done)
			starts[#starts+1] = task.key; callbacks[task.key] = done
		end)
		local tasks = {a={key="a"}, b={key="b"}, c={key="c"}}
		local results = pool:step(tasks)
		assert.same({"a", "b"}, starts)
		assert.equal("running", results.a.status)
		assert.equal("deferred", results.c.status)
		pool:step(tasks); assert.equal(2, #starts)
		callbacks.a({status="unconfirmed"})
		results = pool:step(tasks)
		assert.equal("unconfirmed", results.a.status)
		assert.same({"a", "b", "c"}, starts)
		pool:step(tasks); assert.equal(3, #starts)
	end)
	it("turns spawn failure into retryable error without leaking capacity", function()
		local pool = workers.new(function() error("missing executable") end)
		assert.equal("error", pool:step({a={key="a"}}).a.status)
		assert.same({}, pool:step({}))
	end)
end)
